### ISSUE TITLE
Documentation 

### ISSUE THREAD

**Issue by vpllion** [ebalduf/Tripleo-solidfire-templates#1]
Hi Abdul, 
Could you please help me with documentation or Readme.md

I wanna rid of from below warning

Warning]	Warning
The SolidFire driver creates a unique account prefixed with $cinder-volume-service-hostname-$tenant-id on the SolidFire cluster for each tenant that accesses the cluster through the Volume API. Unfortunately, this account formation results in issues for High Availability (HA) installations and installations where the cinder-volume service can move to a new node. HA installations can return an Account Not Found error because the call to the SolidFire cluster is not always going to be sent from the same node. In installations where the cinder-volume service moves to a new node, the same issue can occur when you perform operations on existing volumes, such as clone, extend, delete, and so on.

**Comment by ebalduf** [comment]
If you are using a newer version of OpenStack (post IceHouse) this issue is no longer an issue. 
Check out the document for the latest SolidFire driver (for the Ocata release) here https://docs.openstack.org/ocata/config-reference/block-storage/drivers/solidfire-volume-driver.html , I had updated the document to indicate that it was IceHouse where that was fixed. 

 If you are using TripleO, there is a good chance you might be using RedHat (or CentOS) and I would now recommend using the 'Custom Storage Backend' feature in TripleO instead of this. While this will still work, there are a couple more things you need to do to get it all working. I know, I should have documented it better, when I found that RedHat had added the 'Custom Block Storage Backend' it didn't make much sense to keep going. Here is the document to the custom backend stuff.  https://access.redhat.com/documentation/en-us/red_hat_openstack_platform/11/html/custom_block_storage_back_end_deployment_guide/

Unfortunately I no longer work for SolidFire/NetApp, but jump on one of their Community channels and ask for the document I wrote with details on how to make this 'Customer backend' stuff work.  One other word of advice, always put a 'host=solidfire' in the SolidFire stanza, it will make it so any of your OpenStack controllers can send requests to the SolidFire.

**Comment by vpllion** [comment]
yaa :+1: thanks, I am using OSP 10 with 3 controller nodes. Was missing parameter *sf_emulate_512= True*
It's working for me now.

**Comment by vpllion** [comment]
closing it, As it seems working now without any problem
